name: Nightly Refresh

permissions:
  contents: write

on:
  push:
    branches: [ main ]
  workflow_dispatch: {}
  schedule:
    - cron: "30 4 * * *"

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Show runner info
        run: |
          echo "Runner OK. This proves the workflow is registered."
