name: Nightly Refresh

permissions:
  contents: write

on:
  schedule:
    - cron: "30 4 * * *"
  workflow_dispatch: {}

jobs:
  refresh:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (full history)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Show previous xgxa (if any)
        run: |
          mkdir -p data/cache
          if [ -f data/cache/xgxa_players.csv ]; then
            ls -lh data/cache/xgxa_players.csv || true
            cp data/cache/xgxa_players.csv /tmp/prev_xgxa.csv || true
          fi

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Phase 1 — Fetch FPL
        run: python pipeline/fetch_fpl_data.py all

      - name: Phase 2 — Ingest xG/xA (Understat first)
        run: |
          sed -i 's/^\(\s*provider\s*=\s*\).*/\1"understat"/' configs/config.toml || true
          python pipeline/ingest_xgxa.py --season 2024 || true
          BYTES=$(wc -c < data/cache/xgxa_players.csv 2>/dev/null || echo 0)
          echo "Understat xgxa size: $BYTES bytes"
          if [ "$BYTES" -lt 1000 ]; then
            echo "Too small — trying FBref..."
            sed -i 's/^\(\s*provider\s*=\s*\).*/\1"fbref"/' configs/config.toml || true
            python pipeline/ingest_xgxa.py --season 2024 || true
          fi

      - name: Finalize xgxa (fallback to previous if still tiny)
        run: |
          BYTES=$(wc -c < data/cache/xgxa_players.csv 2>/dev/null || echo 0)
          echo "Final xgxa size after retries: $BYTES bytes"
          if [ "$BYTES" -lt 1000 ] && [ -f /tmp/prev_xgxa.csv ]; then
            echo "Still tiny — restoring previous xgxa_players.csv"
            cp /tmp/prev_xgxa.csv data/cache/xgxa_players.csv
          fi
          test -f data/cache/xgxa_players.csv
          ls -lh data/cache/xgxa_players.csv

      - name: Phase 3 — Compute projections (1, 3, 5)
        run: |
          python pipeline/compute_phase3.py --next_n 1
          python pipeline/compute_phase3.py --next_n 3
          python pipeline/compute_phase3.py --next_n 5

      - name: Upload cache as artifact (optional)
        uses: actions/upload-artifact@v4
        with:
          name: data-cache
          path: data/cache

      - name: Commit cache back to repo
        run: |
          git config user.name "github-actions"
          git config user.email "actions@users.noreply.github.com"
          git add data/cache/xgxa_players.csv || true
          git add data/cache/projections_next_gw.csv || true
          git add data/cache/projections_next_3gws.csv || true
          git add data/cache/projections_next_5gws.csv || true
          git add data/cache/captaincy_rankings.csv || true
          git commit -m "Nightly cache update" || echo "No changes"
          git push
